mappings:
  HtmlEditorFieldShort: Sunnysideup\CleanerTinyMCEConfig\Forms\HtmlEditorFieldShort
  HTMLEditorFieldShort_ConfigInterface: Sunnysideup\CleanerTinyMCEConfig\Forms\HTMLEditorFieldShort_ConfigInterface
  HTMLEditorFieldShort_Config: Sunnysideup\CleanerTinyMCEConfig\Forms\HTMLEditorFieldShort_Config
